### PR TITLE
Frontend changes

### PR DESCRIPTION
**Pull request by Clittle01**
a simple welcome page with a section for the user to enter their name.

### CODE REVIEW

**Review by MGweh0 — APPROVED** [review]
Hey, Carlos, great job with the back-end, everything looks good so far.

**Comment by Ranger-Jim** [comment]
The welcome page looks nice. Is this using our backend logic at all or is all of the logic now in the App.js file? Sorry, first time looking at frontend stuff.

**Review by Ranger-Jim — APPROVED** [review]

**Comment by jpandher0** [comment]
> The welcome page looks nice. Is this using our backend logic at all or is all of the logic now in the App.js file? Sorry, first time looking at frontend stuff.

Seems like the branch was made off of when our backend was accidentally deleted off of front end, so right now it seems like the base framework for the front end. We just need to include the APIs which I can put in a new PR. @Clittle01 after we're done with iteration2 and ready to merge, we'll have to decline this PR or update it to include the backend.

**Review by jpandher0 — CHANGES_REQUESTED** [review]
readd backend

**Comment by Clittle01** [comment]
> Hey, Carlos, great job with the back-end, everything looks good so far.

thank you! I appreciate that

**Comment by Clittle01** [comment]
> The welcome page looks nice. Is this using our backend logic at all or is all of the logic now in the App.js file? Sorry, first time looking at frontend stuff.

Thank you! & yes this all of the logic for the front end App.JS. Let me know if you have any other question.

**Review by jpandher0 — APPROVED** [review]

**Pull request merged**
